### ISSUE TITLE
(Question) It support the "This Week in Rust" blog?

### ISSUE THREAD

**Issue by hardBSDk** [Atticus64/news#4]
https://this-week-in-rust.org/

**Comment by Atticus64** [comment]
> https://this-week-in-rust.org/

@hardBSDk  Yes, the blog is used to get the rust news 😄☕

**Comment by Atticus64** [comment]
```rs
const RUST_WEEKLY_URL: &str = "https://this-week-in-rust.org/blog/archives/index.html";
```

In the file `news/src/scrape/issues/rust.rs` is used this constant to get all the posts of rust weekly
